# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate iced-x86

Name:           rust-iced-x86
Version:        1.21.0
Release:        %autorelease
Summary:        Iced-x86 is a blazing fast and correct x86/x64 disassembler, assembler and instruction decoder written in Rust

License:        MIT
URL:            https://crates.io/crates/iced-x86
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Iced-x86 is a blazing fast and correct x86/x64 disassembler, assembler
and instruction decoder written in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+__internal_flip-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+__internal_flip-devel %{_description}

This package contains library source intended for building other packages which
use the "__internal_flip" feature of the "%{crate}" crate.

%files       -n %{name}+__internal_flip-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+block_encoder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+block_encoder-devel %{_description}

This package contains library source intended for building other packages which
use the "block_encoder" feature of the "%{crate}" crate.

%files       -n %{name}+block_encoder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+code_asm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+code_asm-devel %{_description}

This package contains library source intended for building other packages which
use the "code_asm" feature of the "%{crate}" crate.

%files       -n %{name}+code_asm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+db-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+db-devel %{_description}

This package contains library source intended for building other packages which
use the "db" feature of the "%{crate}" crate.

%files       -n %{name}+db-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+decoder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+decoder-devel %{_description}

This package contains library source intended for building other packages which
use the "decoder" feature of the "%{crate}" crate.

%files       -n %{name}+decoder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoder-devel %{_description}

This package contains library source intended for building other packages which
use the "encoder" feature of the "%{crate}" crate.

%files       -n %{name}+encoder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+exhaustive_enums-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+exhaustive_enums-devel %{_description}

This package contains library source intended for building other packages which
use the "exhaustive_enums" feature of the "%{crate}" crate.

%files       -n %{name}+exhaustive_enums-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fast_fmt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fast_fmt-devel %{_description}

This package contains library source intended for building other packages which
use the "fast_fmt" feature of the "%{crate}" crate.

%files       -n %{name}+fast_fmt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gas-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gas-devel %{_description}

This package contains library source intended for building other packages which
use the "gas" feature of the "%{crate}" crate.

%files       -n %{name}+gas-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+instr_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+instr_info-devel %{_description}

This package contains library source intended for building other packages which
use the "instr_info" feature of the "%{crate}" crate.

%files       -n %{name}+instr_info-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+intel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+intel-devel %{_description}

This package contains library source intended for building other packages which
use the "intel" feature of the "%{crate}" crate.

%files       -n %{name}+intel-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lazy_static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lazy_static-devel %{_description}

This package contains library source intended for building other packages which
use the "lazy_static" feature of the "%{crate}" crate.

%files       -n %{name}+lazy_static-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+masm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+masm-devel %{_description}

This package contains library source intended for building other packages which
use the "masm" feature of the "%{crate}" crate.

%files       -n %{name}+masm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mvex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mvex-devel %{_description}

This package contains library source intended for building other packages which
use the "mvex" feature of the "%{crate}" crate.

%files       -n %{name}+mvex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nasm-devel %{_description}

This package contains library source intended for building other packages which
use the "nasm" feature of the "%{crate}" crate.

%files       -n %{name}+nasm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_d3now-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_d3now-devel %{_description}

This package contains library source intended for building other packages which
use the "no_d3now" feature of the "%{crate}" crate.

%files       -n %{name}+no_d3now-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_evex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_evex-devel %{_description}

This package contains library source intended for building other packages which
use the "no_evex" feature of the "%{crate}" crate.

%files       -n %{name}+no_evex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_std-devel %{_description}

This package contains library source intended for building other packages which
use the "no_std" feature of the "%{crate}" crate.

%files       -n %{name}+no_std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_vex-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_vex-devel %{_description}

This package contains library source intended for building other packages which
use the "no_vex" feature of the "%{crate}" crate.

%files       -n %{name}+no_vex-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_xop-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_xop-devel %{_description}

This package contains library source intended for building other packages which
use the "no_xop" feature of the "%{crate}" crate.

%files       -n %{name}+no_xop-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+op_code_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+op_code_info-devel %{_description}

This package contains library source intended for building other packages which
use the "op_code_info" feature of the "%{crate}" crate.

%files       -n %{name}+op_code_info-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
