# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate opentelemetry

Name:           rust-opentelemetry0.27
Version:        0.27.1
Release:        %autorelease
Summary:        OpenTelemetry API for Rust

License:        Apache-2.0
URL:            https://crates.io/crates/opentelemetry
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          opentelemetry-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
OpenTelemetry API for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-core" feature of the "%{crate}" crate.

%files       -n %{name}+futures-core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-sink-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-sink-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-sink" feature of the "%{crate}" crate.

%files       -n %{name}+futures-sink-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+internal-logs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+internal-logs-devel %{_description}

This package contains library source intended for building other packages which
use the "internal-logs" feature of the "%{crate}" crate.

%files       -n %{name}+internal-logs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+logs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+logs-devel %{_description}

This package contains library source intended for building other packages which
use the "logs" feature of the "%{crate}" crate.

%files       -n %{name}+logs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+metrics-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+metrics-devel %{_description}

This package contains library source intended for building other packages which
use the "metrics" feature of the "%{crate}" crate.

%files       -n %{name}+metrics-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+otel_unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+otel_unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "otel_unstable" feature of the "%{crate}" crate.

%files       -n %{name}+otel_unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pin-project-lite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pin-project-lite-devel %{_description}

This package contains library source intended for building other packages which
use the "pin-project-lite" feature of the "%{crate}" crate.

%files       -n %{name}+pin-project-lite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+spec_unstable_logs_enabled-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spec_unstable_logs_enabled-devel %{_description}

This package contains library source intended for building other packages which
use the "spec_unstable_logs_enabled" feature of the "%{crate}" crate.

%files       -n %{name}+spec_unstable_logs_enabled-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+testing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+testing-devel %{_description}

This package contains library source intended for building other packages which
use the "testing" feature of the "%{crate}" crate.

%files       -n %{name}+testing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+thiserror-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+thiserror-devel %{_description}

This package contains library source intended for building other packages which
use the "thiserror" feature of the "%{crate}" crate.

%files       -n %{name}+thiserror-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trace-devel %{_description}

This package contains library source intended for building other packages which
use the "trace" feature of the "%{crate}" crate.

%files       -n %{name}+trace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
