# Generated by rust2rpm 28
%bcond check 1

%global crate wild-linker

Name:           rust-wild-linker
Version:        0.8.0
Release:        %autorelease
Summary:        Very fast linker for Linux

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/wild-linker
Source:         %{crates_source}
Patch:          fix-missing-dep.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A very fast linker for Linux.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/wild

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
