# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate tokio-vsock

Name:           rust-tokio-vsock
Version:        0.7.2
Release:        %autorelease
Summary:        Asynchronous Virtio socket support for Rust

License:        Apache-2.0
URL:            https://crates.io/crates/tokio-vsock
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Asynchronous Virtio socket support for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/THIRD-PARTY-LICENSES
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+axum08-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+axum08-devel %{_description}

This package contains library source intended for building other packages which
use the "axum08" feature of the "%{crate}" crate.

%files       -n %{name}+axum08-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic010-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic010-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic010" feature of the "%{crate}" crate.

%files       -n %{name}+tonic010-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic011-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic011-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic011" feature of the "%{crate}" crate.

%files       -n %{name}+tonic011-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic012-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic012-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic012" feature of the "%{crate}" crate.

%files       -n %{name}+tonic012-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic013-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic013-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic013" feature of the "%{crate}" crate.

%files       -n %{name}+tonic013-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic014-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic014-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic014" feature of the "%{crate}" crate.

%files       -n %{name}+tonic014-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic05-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic05-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic05" feature of the "%{crate}" crate.

%files       -n %{name}+tonic05-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic06-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic06-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic06" feature of the "%{crate}" crate.

%files       -n %{name}+tonic06-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic07-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic07-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic07" feature of the "%{crate}" crate.

%files       -n %{name}+tonic07-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic08-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic08-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic08" feature of the "%{crate}" crate.

%files       -n %{name}+tonic08-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tonic09-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tonic09-devel %{_description}

This package contains library source intended for building other packages which
use the "tonic09" feature of the "%{crate}" crate.

%files       -n %{name}+tonic09-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
