# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate symbolic-demangle

Name:           rust-symbolic-demangle
Version:        12.17.2
Release:        %autorelease
Summary:        Library to demangle symbols from various languages and compilers

License:        MIT
URL:            https://crates.io/crates/symbolic-demangle
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library to demangle symbols from various languages and compilers.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cc-devel %{_description}

This package contains library source intended for building other packages which
use the "cc" feature of the "%{crate}" crate.

%files       -n %{name}+cc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cpp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cpp-devel %{_description}

This package contains library source intended for building other packages which
use the "cpp" feature of the "%{crate}" crate.

%files       -n %{name}+cpp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cpp_demangle-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cpp_demangle-devel %{_description}

This package contains library source intended for building other packages which
use the "cpp_demangle" feature of the "%{crate}" crate.

%files       -n %{name}+cpp_demangle-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+msvc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+msvc-devel %{_description}

This package contains library source intended for building other packages which
use the "msvc" feature of the "%{crate}" crate.

%files       -n %{name}+msvc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+msvc-demangler-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+msvc-demangler-devel %{_description}

This package contains library source intended for building other packages which
use the "msvc-demangler" feature of the "%{crate}" crate.

%files       -n %{name}+msvc-demangler-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rust-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rust-devel %{_description}

This package contains library source intended for building other packages which
use the "rust" feature of the "%{crate}" crate.

%files       -n %{name}+rust-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustc-demangle-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustc-demangle-devel %{_description}

This package contains library source intended for building other packages which
use the "rustc-demangle" feature of the "%{crate}" crate.

%files       -n %{name}+rustc-demangle-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+swift-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+swift-devel %{_description}

This package contains library source intended for building other packages which
use the "swift" feature of the "%{crate}" crate.

%files       -n %{name}+swift-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
