# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate perfetto-recorder

Name:           rust-perfetto-recorder
Version:        0.3.2
Release:        %autorelease
Summary:        Low overhead way to record perfetto traces from Rust code

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/perfetto-recorder
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          perfetto-recorder-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A low overhead way to record perfetto traces from Rust code.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+enable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+enable-devel %{_description}

This package contains library source intended for building other packages which
use the "enable" feature of the "%{crate}" crate.

%files       -n %{name}+enable-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fastant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fastant-devel %{_description}

This package contains library source intended for building other packages which
use the "fastant" feature of the "%{crate}" crate.

%files       -n %{name}+fastant-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
