# Generated by rust2rpm 28
%bcond check 1

%global crate deno

Name:           rust-deno
Version:        2.6.6
Release:        %autorelease
Summary:        Deno executable

License:        MIT
URL:            https://crates.io/crates/deno
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          deno-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Provides the deno executable.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license tsc/dts/node/LICENSE
%license tsc/dts/node/undici/LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/deno

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
