# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate regex

Name:           rust-regex0.2
Version:        0.2.11
Release:        %autorelease
Summary:        Implementation of regular expressions for Rust

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/regex
Source:         %{crates_source}
Patch:          fix-python3-shebang.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An implementation of regular expressions for Rust. This implementation
uses finite automata and guarantees linear time matching on all inputs.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/HACKING.md
%doc %{crate_instdir}/PERFORMANCE.md
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/UNICODE.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pattern-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pattern-devel %{_description}

This package contains library source intended for building other packages which
use the "pattern" feature of the "%{crate}" crate.

%files       -n %{name}+pattern-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd-accel-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd-accel-devel %{_description}

This package contains library source intended for building other packages which
use the "simd-accel" feature of the "%{crate}" crate.

%files       -n %{name}+simd-accel-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
