# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate libwild

Name:           rust-libwild
Version:        0.8.0
Release:        %autorelease
Summary:        Library that provides a fast Linux linker

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/libwild
Source:         %{crates_source}
Patch:          libwild-dont-update-perf_event.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library that provides a fast Linux linker.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fork-devel %{_description}

This package contains library source intended for building other packages which
use the "fork" feature of the "%{crate}" crate.

%files       -n %{name}+fork-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+perfetto-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+perfetto-devel %{_description}

This package contains library source intended for building other packages which
use the "perfetto" feature of the "%{crate}" crate.

%files       -n %{name}+perfetto-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wip-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wip-devel %{_description}

This package contains library source intended for building other packages which
use the "wip" feature of the "%{crate}" crate.

%files       -n %{name}+wip-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
