# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate capacity_builder

Name:           rust-capacity_builder
Version:        0.5.0
Release:        %autorelease
Summary:        Builders where the code to calculate the capacity is the same as the code to write what's being built

License:        MIT
URL:            https://crates.io/crates/capacity_builder
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Builders where the code to calculate the capacity is the same as the
code to write what's being built.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ecow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ecow-devel %{_description}

This package contains library source intended for building other packages which
use the "ecow" feature of the "%{crate}" crate.

%files       -n %{name}+ecow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hipstr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hipstr-devel %{_description}

This package contains library source intended for building other packages which
use the "hipstr" feature of the "%{crate}" crate.

%files       -n %{name}+hipstr-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
